-- this file is generated by program!
-- don't change it manaully.
-- source file: building.xls
-- created at: Wed Mar 25 16:52:12 2015


local data = {}

data[1] = { id = 1,  name = "house",  use_money = 1000,  use_food = 123,  is_init = true,  defense = 100,  aadd = {1,2,3},  ddff = {"sdf","23e","s"},  ffdd = {true,false,true}, }
data[2] = { id = 2,  name = "house2",  use_money = 123,  use_food = 322,  is_init = true,  defense = 0,  aadd = {1,2,3},  ddff = {"你好","你在哪"},  ffdd = {true,false}, }
data[3] = { id = 3,  name = "",  use_money = 456,  use_food = 12,  is_init = false,  defense = 130,  aadd = {3,2,5},  ddff = {"我在这里啊","你在那","呢"},  ffdd = {false,true}, }
data[4] = { id = 4,  name = "farm",  use_money = 100,  use_food = 234,  is_init = false,  defense = 200,  aadd = {2,3},  ddff = {"df","ssd","dd","dd"},  ffdd = {}, }
data[5] = { id = 5,  name = "house5",  use_money = 0,  use_food = 424,  is_init = false,  defense = 234,  aadd = {3,6,6,7},  ddff = {"ss","d","d","d"},  ffdd = {true,true}, }
data[6] = { id = 6,  name = "horse3",  use_money = 200,  use_food = 121,  is_init = false,  defense = 333,  aadd = {},  ddff = {"2e","w","e","we"},  ffdd = {false,false,false,false}, }
return data
