-- this file is generated by program!
-- don't change it manaully.
-- source file: TABLE_英雄经验表.xlsx
-- created at: Thu Mar 26 10:47:55 2015


local data = {}

data[1] = { level = 1,  Exp1 = 0,  Exp2 = 0,  Exp3 = 0}
data[2] = { level = 2,  Exp1 = 10,  Exp2 = 15,  Exp3 = 21}
data[3] = { level = 3,  Exp1 = 58,  Exp2 = 87,  Exp3 = 117}
data[4] = { level = 4,  Exp1 = 160,  Exp2 = 240,  Exp3 = 321}
data[5] = { level = 5,  Exp1 = 329,  Exp2 = 492,  Exp3 = 658}
data[6] = { level = 6,  Exp1 = 574,  Exp2 = 860,  Exp3 = 1148}
data[7] = { level = 7,  Exp1 = 905,  Exp2 = 1357,  Exp3 = 1810}
data[8] = { level = 8,  Exp1 = 1330,  Exp2 = 1995,  Exp3 = 2660}
data[9] = { level = 9,  Exp1 = 1857,  Exp2 = 2785,  Exp3 = 3714}
data[10] = { level = 10,  Exp1 = 2493,  Exp2 = 3738,  Exp3 = 4985}
data[11] = { level = 11,  Exp1 = 3244,  Exp2 = 4865,  Exp3 = 6488}
data[12] = { level = 12,  Exp1 = 4116,  Exp2 = 6174,  Exp3 = 8233}
data[13] = { level = 13,  Exp1 = 5117,  Exp2 = 7674,  Exp3 = 10234}
data[14] = { level = 14,  Exp1 = 6250,  Exp2 = 9375,  Exp3 = 12501}
data[15] = { level = 15,  Exp1 = 7522,  Exp2 = 11283,  Exp3 = 15045}
data[16] = { level = 16,  Exp1 = 8939,  Exp2 = 13407,  Exp3 = 17877}
data[17] = { level = 17,  Exp1 = 10504,  Exp2 = 15754,  Exp3 = 21006}
data[18] = { level = 18,  Exp1 = 12222,  Exp2 = 18332,  Exp3 = 24444}
data[19] = { level = 19,  Exp1 = 14099,  Exp2 = 21147,  Exp3 = 28198}
data[20] = { level = 20,  Exp1 = 16140,  Exp2 = 24207,  Exp3 = 32279}
data[21] = { level = 21,  Exp1 = 18346,  Exp2 = 27519,  Exp3 = 36694}
data[22] = { level = 22,  Exp1 = 20726,  Exp2 = 31088,  Exp3 = 41453}
data[23] = { level = 23,  Exp1 = 23282,  Exp2 = 34923,  Exp3 = 46565}
data[24] = { level = 24,  Exp1 = 26019,  Exp2 = 39027,  Exp3 = 52037}
data[25] = { level = 25,  Exp1 = 28940,  Exp2 = 43408,  Exp3 = 57878}
data[26] = { level = 26,  Exp1 = 32049,  Exp2 = 48072,  Exp3 = 64096}
data[27] = { level = 27,  Exp1 = 35350,  Exp2 = 53024,  Exp3 = 70699}
data[28] = { level = 28,  Exp1 = 38847,  Exp2 = 58270,  Exp3 = 77694}
data[29] = { level = 29,  Exp1 = 42544,  Exp2 = 63816,  Exp3 = 85088}
data[30] = { level = 30,  Exp1 = 46446,  Exp2 = 69667,  Exp3 = 92889}
data[31] = { level = 31,  Exp1 = 50554,  Exp2 = 75829,  Exp3 = 101104}
data[32] = { level = 32,  Exp1 = 54873,  Exp2 = 82307,  Exp3 = 109741}
data[33] = { level = 33,  Exp1 = 59405,  Exp2 = 89106,  Exp3 = 118806}
data[34] = { level = 34,  Exp1 = 64154,  Exp2 = 96231,  Exp3 = 128306}
data[35] = { level = 35,  Exp1 = 69126,  Exp2 = 103687,  Exp3 = 138248}
data[36] = { level = 36,  Exp1 = 74321,  Exp2 = 111480,  Exp3 = 148638}
data[37] = { level = 37,  Exp1 = 79744,  Exp2 = 119614,  Exp3 = 159483}
data[38] = { level = 38,  Exp1 = 85397,  Exp2 = 128094,  Exp3 = 170790}
data[39] = { level = 39,  Exp1 = 91284,  Exp2 = 136925,  Exp3 = 182564}
data[40] = { level = 40,  Exp1 = 97408,  Exp2 = 146111,  Exp3 = 194812}
data[41] = { level = 41,  Exp1 = 103772,  Exp2 = 155658,  Exp3 = 207541}
data[42] = { level = 42,  Exp1 = 110380,  Exp2 = 165569,  Exp3 = 220756}
data[43] = { level = 43,  Exp1 = 117234,  Exp2 = 175850,  Exp3 = 234464}
data[44] = { level = 44,  Exp1 = 124337,  Exp2 = 186504,  Exp3 = 248670}
data[45] = { level = 45,  Exp1 = 131692,  Exp2 = 197536,  Exp3 = 263380}
data[46] = { level = 46,  Exp1 = 139302,  Exp2 = 208951,  Exp3 = 278600}
data[47] = { level = 47,  Exp1 = 147170,  Exp2 = 220753,  Exp3 = 294336}
data[48] = { level = 48,  Exp1 = 155299,  Exp2 = 232947,  Exp3 = 310594}
data[49] = { level = 49,  Exp1 = 163692,  Exp2 = 245536,  Exp3 = 327379}
data[50] = { level = 50,  Exp1 = 172352,  Exp2 = 258525,  Exp3 = 344697}
data[51] = { level = 51,  Exp1 = 181280,  Exp2 = 271917,  Exp3 = 362553}
data[52] = { level = 52,  Exp1 = 190480,  Exp2 = 285717,  Exp3 = 380953}
data[53] = { level = 53,  Exp1 = 199555,  Exp2 = 299929,  Exp3 = 399903}
data[54] = { level = 54,  Exp1 = 209707,  Exp2 = 314557,  Exp3 = 419407}
data[55] = { level = 55,  Exp1 = 219739,  Exp2 = 329605,  Exp3 = 439471}
data[56] = { level = 56,  Exp1 = 230054,  Exp2 = 345077,  Exp3 = 460100}
data[57] = { level = 57,  Exp1 = 240654,  Exp2 = 360977,  Exp3 = 481300}
data[58] = { level = 58,  Exp1 = 251542,  Exp2 = 377308,  Exp3 = 503075}
data[59] = { level = 59,  Exp1 = 262720,  Exp2 = 394075,  Exp3 = 525431}
data[60] = { level = 60,  Exp1 = 274191,  Exp2 = 411281,  Exp3 = 548372}
data[61] = { level = 61,  Exp1 = 285957,  Exp2 = 428936,  Exp3 = 571904}
data[62] = { level = 62,  Exp1 = 298021,  Exp2 = 447032,  Exp3 = 596032}
data[63] = { level = 63,  Exp1 = 310385,  Exp2 = 465578,  Exp3 = 620761}
data[64] = { level = 64,  Exp1 = 323052,  Exp2 = 484578,  Exp3 = 646095}
data[65] = { level = 65,  Exp1 = 336024,  Exp2 = 504036,  Exp3 = 672040}
data[66] = { level = 66,  Exp1 = 349304,  Exp2 = 523956,  Exp3 = 698600}
data[67] = { level = 67,  Exp1 = 362894,  Exp2 = 544341,  Exp3 = 725780}
data[68] = { level = 68,  Exp1 = 376796,  Exp2 = 565194,  Exp3 = 753585}
data[69] = { level = 69,  Exp1 = 391013,  Exp2 = 586520,  Exp3 = 782019}
data[70] = { level = 70,  Exp1 = 405547,  Exp2 = 608321,  Exp3 = 811087}
data[71] = { level = 71,  Exp1 = 420401,  Exp2 = 630602,  Exp3 = 840794}
data[72] = { level = 72,  Exp1 = 435576,  Exp2 = 653364,  Exp3 = 871145}
data[73] = { level = 73,  Exp1 = 451075,  Exp2 = 676613,  Exp3 = 902144}
data[74] = { level = 74,  Exp1 = 466901,  Exp2 = 700352,  Exp3 = 933795}
data[75] = { level = 75,  Exp1 = 483055,  Exp2 = 724583,  Exp3 = 966103}
data[76] = { level = 76,  Exp1 = 499540,  Exp2 = 749310,  Exp3 = 999073}
data[77] = { level = 77,  Exp1 = 516358,  Exp2 = 774537,  Exp3 = 1032709}
data[78] = { level = 78,  Exp1 = 533511,  Exp2 = 800267,  Exp3 = 1067016}
data[79] = { level = 79,  Exp1 = 551002,  Exp2 = 826503,  Exp3 = 1101997}
data[80] = { level = 80,  Exp1 = 568832,  Exp2 = 853248,  Exp3 = 1137658}

return data
