using System;
namespace SLua {
	public partial class LuaObject {
		public static void BindCustom(IntPtr l) {
			Lua_Custom.reg(l);
			Lua_Deleg.reg(l);
			Lua_HelloWorld.reg(l);
			Lua_DG_Tweening_Plugins_Vector3Plugin.reg(l);
			Lua_DG_Tweening_RotateMode.reg(l);
			Lua_DG_Tweening_DOTween.reg(l);
			Lua_DG_Tweening_Core_Extensions.reg(l);
			Lua_DG_Tweening_Color2.reg(l);
			Lua_DG_Tweening_TweenSettingsExtensions.reg(l);
			Lua_DG_Tweening_Plugins_Core_PathCore_Path.reg(l);
			Lua_DG_Tweening_Core_ABSSequentiable.reg(l);
			Lua_DG_Tweening_Tween.reg(l);
			Lua_DG_Tweening_Tweener.reg(l);
			Lua_DG_Tweening_Plugins_RectPlugin.reg(l);
			Lua_DG_Tweening_Plugins_Options_RectOptions.reg(l);
			Lua_DG_Tweening_Plugins_Options_ColorOptions.reg(l);
			Lua_DG_Tweening_LoopType.reg(l);
			Lua_DG_Tweening_TweenExtensions.reg(l);
			Lua_DG_Tweening_Plugins_Vector4Plugin.reg(l);
			Lua_DG_Tweening_Plugins_RectOffsetPlugin.reg(l);
			Lua_DG_Tweening_Plugins_Options_NoOptions.reg(l);
			Lua_DG_Tweening_Plugins_Vector3ArrayPlugin.reg(l);
			Lua_DG_Tweening_TweenType.reg(l);
			Lua_DG_Tweening_LogBehaviour.reg(l);
			Lua_DG_Tweening_TweenParams.reg(l);
			Lua_DG_Tweening_Plugins_QuaternionPlugin.reg(l);
			Lua_DG_Tweening_Plugins_PathPlugin.reg(l);
			Lua_DG_Tweening_Plugins_Options_Vector3ArrayOptions.reg(l);
			Lua_DG_Tweening_Plugins_Options_QuaternionOptions.reg(l);
			Lua_DG_Tweening_Plugins_IntPlugin.reg(l);
			Lua_DG_Tweening_Plugins_Options_OrientType.reg(l);
			Lua_DG_Tweening_Plugins_Options_PathOptions.reg(l);
			Lua_DG_Tweening_Core_Easing_Bounce.reg(l);
			Lua_DG_Tweening_Ease.reg(l);
			Lua_DG_Tweening_Plugins_StringPlugin.reg(l);
			Lua_DG_Tweening_Plugins_ColorPlugin.reg(l);
			Lua_DG_Tweening_PathMode.reg(l);
			Lua_DG_Tweening_Plugins_Options_StringOptions.reg(l);
			Lua_DG_Tweening_Plugins_FloatPlugin.reg(l);
			Lua_DG_Tweening_Sequence.reg(l);
			Lua_DG_Tweening_Plugins_Options_VectorOptions.reg(l);
			Lua_DG_Tweening_Plugins_Vector2Plugin.reg(l);
			Lua_DG_Tweening_Core_Easing_EaseManager.reg(l);
			Lua_DG_Tweening_Core_DOTweenComponent.reg(l);
			Lua_DG_Tweening_Plugins_UintPlugin.reg(l);
			Lua_DG_Tweening_AutoPlay.reg(l);
			Lua_DG_Tweening_UpdateType.reg(l);
			Lua_DG_Tweening_ShortcutExtensions.reg(l);
			Lua_DG_Tweening_Plugins_Options_FloatOptions.reg(l);
			Lua_DG_Tweening_PathType.reg(l);
			Lua_DG_Tweening_AxisConstraint.reg(l);
			Lua_DG_Tweening_ShortcutExtensions.reg(l);
			Lua_DG_Tweening_ShortcutExtensions.reg(l);
		}
	}
}
